ZZIN-27-[MERGE]: ✅ didSelect 및 stories grouping 해결
Team-Ddobaegi/ZZin pull request #132
Opened 2024-01-07 14:45 UTC by Madman-dev

- cell 탭 시 cell의 하이라이트가 지속되는 이슈 해결
- main page 상단 story의 구역별 grouping 완료

2024-01-07 14:47 UTC, angwoo0503 approved these changes
확인했습니다 고생하셨어유

2024-01-07 14:54 UTC, BoKyeongee requested changes
강남구만 두 번 나오는 버그까지 같이 수정 부탁드릴게요!

2024-01-07 14:54 UTC, BoKyeongee commented on ZZin/MainPage/View/TableViewCell/LocalTableViewCell.swift
> +        print("========== 지역이 출력:", filteredData)
강남구가 두 번 나오네요!
업데이트를 위한 merge기 때문에 이 부분까지 해결해주시는게 좋을 것 같습니다!

2024-01-07 14:56 UTC, Madman-dev commented on ZZin/MainPage/View/TableViewCell/LocalTableViewCell.swift
> +        print("========== 지역이 출력:", filteredData)
수정해서 다시 올려보겠습니다~

2024-02-27 08:20 UTC, Madman-dev commented
요청사항 업데이트 이후 머지 완료
따라서 해당 PR은 닫습니다.

2024-02-27 08:20 UTC, closed without merging